# Thanks to: https://markkarpov.com/post/github-actions-for-haskell-ci.html
name: CI

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  cabal:
    name: Cabal ${{ matrix.cabal }} / GHC ${{ matrix.ghc }}
    strategy:
      matrix:
        cabal: ["3.2.0.0", "3.4.0.0"]
        ghc: ["8.10.5", "9.0.1"]
        os: [ubuntu-latest]
        exclude:
          - cabal: "3.2.0.0"
            ghc: "9.0.1"
    runs-on: ${{ matrix.os }}
    env:
      CONFIG: "--enable-tests --enable-benchmarks --test-show-details=streaming --test-option=--color --test-option=always"
    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell/actions/setup@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - run: cabal v2-update
    - run: cabal v2-freeze $CONFIG

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: | 
          ${{ runner.os }}-${{ matrix.ghc }}-

    - run: cabal v2-build $CONFIG
    - run: cabal v2-test $CONFIG
    - run: cabal v2-haddock $CONFIG

  stack:
    name: Stack
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["latest"]
        ghc: ["8.10.6"]
    env:
      CONFIG: "--test --bench"
    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell/actions/setup@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        enable-stack: "true"

    - uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('mello.cabal') }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-

    - run: stack build --system-ghc $CONFIG --no-run-tests --no-run-benchmarks --only-dependencies
    - run: stack build --system-ghc $CONFIG --no-run-tests --no-run-benchmarks
    - run: stack test  --system-ghc

